version: "2"
services:
  magicmirror:
    image: magicmirror
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.magicmirror
    container_name: magicmirror
    volumes:
      - "magicmirror:${MAGIC_MIRROR_CONTAINER}"
    ports:
      - "${MAGIC_MIRROR_PORT}:443"

volumes:
  magicmirror:
    external:
      name: ${MAGIC_MIRROR_HOST}
